const sampleVideos = [
  {
    videotitle: "Learn Web Development in 2024",
    filename: "web-dev-2024.mp4",
    filepath: "uploads/web-dev-2024.mp4",
    filetype: "video/mp4",
    filesize: "45000000",
    videochanel: "Tech Academy",
    Like: 256,
    views: 5420,
    uploader: "tech_academy_01",
  },
  {
    videotitle: "React Hooks Explained - Complete Guide",
    filename: "react-hooks.mp4",
    filepath: "uploads/react-hooks.mp4",
    filetype: "video/mp4",
    filesize: "38000000",
    videochanel: "Code Masters",
    Like: 189,
    views: 3210,
    uploader: "code_masters_02",
  },
  {
    videotitle: "JavaScript Promise Tutorial",
    filename: "js-promises.mp4",
    filepath: "uploads/js-promises.mp4",
    filetype: "video/mp4",
    filesize: "32000000",
    videochanel: "Web Dev Pro",
    Like: 421,
    views: 8950,
    uploader: "webdev_pro_03",
  },
  {
    videotitle: "MongoDB Database Design Best Practices",
    filename: "mongodb-design.mp4",
    filepath: "uploads/mongodb-design.mp4",
    filetype: "video/mp4",
    filesize: "50000000",
    videochanel: "Database Guru",
    Like: 302,
    views: 6780,
    uploader: "db_guru_04",
  },
  {
    videotitle: "Node.js Express Server Setup",
    filename: "nodejs-express.mp4",
    filepath: "uploads/nodejs-express.mp4",
    filetype: "video/mp4",
    filesize: "41000000",
    videochanel: "Backend Warriors",
    Like: 567,
    views: 12340,
    uploader: "backend_warriors_05",
  },
  {
    videotitle: "Next.js Full Stack Development",
    filename: "nextjs-fullstack.mp4",
    filepath: "uploads/nextjs-fullstack.mp4",
    filetype: "video/mp4",
    filesize: "55000000",
    videochanel: "Modern Dev",
    Like: 891,
    views: 18900,
    uploader: "modern_dev_06",
  },
  {
    videotitle: "CSS Grid and Flexbox Mastery",
    filename: "css-layout.mp4",
    filepath: "uploads/css-layout.mp4",
    filetype: "video/mp4",
    filesize: "28000000",
    videochanel: "Design Pro",
    Like: 234,
    views: 4560,
    uploader: "design_pro_07",
  },
  {
    videotitle: "TypeScript for Beginners",
    filename: "typescript-intro.mp4",
    filepath: "uploads/typescript-intro.mp4",
    filetype: "video/mp4",
    filesize: "36000000",
    videochanel: "Code Academy",
    Like: 445,
    views: 9870,
    uploader: "code_academy_08",
  },
  {
    videotitle: "REST API Development Guide",
    filename: "rest-api.mp4",
    filepath: "uploads/rest-api.mp4",
    filetype: "video/mp4",
    filesize: "43000000",
    videochanel: "API Experts",
    Like: 678,
    views: 14560,
    uploader: "api_experts_09",
  },
  {
    videotitle: "Web Security and Authentication",
    filename: "web-security.mp4",
    filepath: "uploads/web-security.mp4",
    filetype: "video/mp4",
    filesize: "47000000",
    videochanel: "Security First",
    Like: 523,
    views: 11230,
    uploader: "security_first_10",
  },
];
export { sampleVideos };

export default sampleVideos;
